#!/bin/bash

eval $(echo "no:global default;fi:normal file;di:directory;ln:symbolic link;pi:named pipe;so:socket;do:door;bd:block device;cd:character device;or:orphan symlink;mi:missing file;su:set uid;sg:set gid;tw:sticky other writable;ow:other writable;st:sticky;ex:executable;"|sed -e 's/:/="/g; s/\;/"\n/g')
{
  IFS=:
  for i in $LS_COLORS
  do
    # includes a long list of file assocations and their respective colors
    # echo -e "\e[${i#*=}m$( x=${i%=*}; [ "${x:0:1}" != "*" ] && [ "${!x}" ] && echo "${!x}" || echo "$x" )\e[m"

    # omits the file associations
    if ! echo "$i" | grep --silent '*' ; then
        echo -e "\\e[${i#*=}m$( x=${i%=*}; [ "${!x}" ] && echo "${!x}" || echo "$x" )\\e[m"
    fi
  done
}
